import React, { useState } from 'react';
import Paywall from './Paywall';

// If you have a Login component, you can import it here:
// import Login from './Login'; 

const App = () => {
  const [showPaywall, setShowPaywall] = useState(false);
  const [showAuthForm, setShowAuthForm] = useState(false);

  // 🛡️ THE BULLETPROOF SWITCH 🛡️
  // This checks if the app is running on the Android phone (localhost/capacitor) 
  // vs running on the internet (Vercel)
  const isNativeApp = typeof window !== 'undefined' && (
    window.location.hostname === 'localhost' || 
    window.location.protocol === 'capacitor:' || 
    window.location.protocol === 'file:'
  );

  // ==========================================
  // 📱 VIEW 1: WHAT HAPPENS INSIDE THE APK 📱
  // ==========================================
  if (isNativeApp) {
    return (
      <div className="min-h-screen bg-white font-sans flex flex-col items-center justify-center p-8 text-center">
        <div className="mb-12">
          <div className="w-16 h-16 bg-blue-600 rounded-2xl flex items-center justify-center text-white font-black text-3xl shadow-xl mx-auto mb-4">C</div>
          <h1 className="text-3xl font-black italic tracking-tighter text-gray-900">CreatorCoach</h1>
          <p className="text-blue-600 font-bold text-sm uppercase tracking-widest mt-2">Your AI Viral Growth Partner</p>
        </div>

        {!showAuthForm ? (
          <div className="w-full max-w-sm space-y-4">
            <button onClick={() => setShowAuthForm(true)} className="w-full bg-blue-600 text-white font-black py-5 rounded-2xl text-xl shadow-lg active:scale-95 transition-all">Sign Up</button>
            <button onClick={() => setShowAuthForm(true)} className="w-full bg-gray-100 text-gray-900 font-black py-5 rounded-2xl text-xl active:scale-95 transition-all">Login</button>
          </div>
        ) : (
          <div className="w-full max-w-sm">
            {/* If you have your <Login /> component, you can put it here instead of this div */}
            <div className="bg-gray-100 p-6 rounded-2xl mb-4 text-left">
              <h3 className="font-black text-gray-900 mb-4 text-xl">Enter VIP Details</h3>
              <input type="email" placeholder="Email" className="w-full p-4 mb-3 rounded-xl border border-gray-300 text-black" />
              <input type="password" placeholder="Password" className="w-full p-4 mb-4 rounded-xl border border-gray-300 text-black" />
              <button className="w-full bg-blue-600 text-white font-black py-4 rounded-xl">Enter App</button>
            </div>
            
            <button onClick={() => setShowAuthForm(false)} className="w-full mt-4 text-gray-400 font-bold text-sm underline">Go Back</button>
          </div>
        )}
      </div>
    );
  }

  // ==============================================
  // 🌐 VIEW 2: WHAT HAPPENS ON THE INSTA LINK 🌐
  // ==============================================
  return (
    <div className="min-h-screen bg-black text-white relative flex flex-col items-center justify-center font-sans">
      <div className="mt-12 mb-8 text-center">
        <div className="w-16 h-16 bg-blue-600 rounded-2xl flex items-center justify-center text-white font-black text-3xl shadow-xl mx-auto mb-4">C</div>
        <h1 className="text-3xl font-black italic tracking-tighter text-white">CreatorCoach</h1>
        <p className="text-blue-500 font-bold text-xs uppercase tracking-widest mt-2">Your AI Viral Growth Partner</p>
      </div>

      <section className="px-6 pb-24 max-w-4xl mx-auto text-center flex-1 flex flex-col justify-center">
        <div className="mb-8">
          <span className="bg-blue-900/50 border border-blue-800 text-blue-400 px-4 py-1.5 rounded-full text-xs font-black uppercase tracking-widest">Free Beta Access</span>
        </div>
        
        <h2 className="text-5xl md:text-7xl font-black mb-6 tracking-tight leading-none text-white">
          Stop Staring at a <span className="text-blue-600">Blank Screen.</span>
        </h2>
        
        <p className="text-lg md:text-xl text-gray-400 max-w-2xl mx-auto mb-10 leading-relaxed">
          The first AI Coach for Indian creators. Viral hooks generated by Llama-3.1 in seconds.
        </p>

        <div className="flex flex-col items-center gap-4">
          <a href="/creator-coach.apk" download className="w-full max-w-sm bg-blue-600 text-white font-black px-8 py-5 rounded-2xl text-xl shadow-[0_0_40px_-10px_rgba(37,99,235,0.5)] active:scale-95 transition-all flex items-center justify-center gap-3">
            Download for Android
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={3} stroke="currentColor" className="w-6 h-6"><path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" /></svg>
          </a>
          <p className="text-sm text-gray-500 font-medium italic mt-2">v1.0.5 • <span className="text-yellow-500 font-bold">₹149 for Lifetime VIP</span></p>
        </div>
      </section>

      {showPaywall && <Paywall onUnlock={() => setShowPaywall(false)} />}
    </div>
  );
};

export default App;